<RootWidget>:
    cols: 3

    MyLayout:
        my_layout_id: 1
        rows: 3
        CustomButton:
            text: "btn 1"
            btn_id: 1
        CustomButton:
            text: "btn 2"
            btn_id: 2
    CustomButton:
        text: "btn 3"
        btn_id: 3
    MyLayout:
        my_layout_id: 2
        rows: 3
        CustomButton:
            text: "btn 4"
            btn_id: 4
        CustomButton:
            text: "btn 5"
            btn_id: 5
        CustomButton:
            text: "btn 6"
            btn_id: 6

#<RootWidget>:
#    cols: 3
#    Button:
#        text: "btn 1"
#    Button:
#        text: "btn 2"
#    Button:
#        text: "btn 3"
